# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb2todotxt < Formula
  desc "Converts pull request tasks from bitbucket to todo txt tasks"
  homepage "https://github.com/scottmmjackson/bb2todotxt"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scottmmjackson/bb2todotxt/releases/download/v0.0.3/bb2todotxt_Darwin_x86_64.tar.gz"
      sha256 "0747212a3efb09cc6991f5343b625c383b0265036a1e54650090282b7cb78461"

      def install
        bin.install "bb2todotxt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scottmmjackson/bb2todotxt/releases/download/v0.0.3/bb2todotxt_Darwin_arm64.tar.gz"
      sha256 "fcdd5fe5e3a0b91c8d7a39f3b91b515e839ed56ca6948c993a1e7423b8f40af3"

      def install
        bin.install "bb2todotxt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scottmmjackson/bb2todotxt/releases/download/v0.0.3/bb2todotxt_Linux_arm64.tar.gz"
      sha256 "c898ded37d257fb5eb7a628fef8ccbb5f948b654f4ea3905e58a13f900bf74da"

      def install
        bin.install "bb2todotxt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scottmmjackson/bb2todotxt/releases/download/v0.0.3/bb2todotxt_Linux_x86_64.tar.gz"
      sha256 "f67482a6b0400d200de545c8ae51ae38e88aa33148b3238afdbcb34651623e8d"

      def install
        bin.install "bb2todotxt"
      end
    end
  end

  test do
    system "#{bin}/bb2todotxt -v"
  end
end
